### ISSUE TITLE
bpfbench source code

### ISSUE THREAD

**Issue by BoardzMaster** [willfindlay/bpfbench#1]
Hi William! How are you doing?  My name is Konstantin. I'm OS kernel engineer and your ebpH thesis is quite an interesting project. I have launched ebpH deamon on my virtual machine to test it. Also, I would like to gather results from the bpfbench like you did. But unfortunately, bpfbench repo is empty. Can you help me with the bench code if it does not bother you? Please email me kostyameskhidze@gmail.com. Thank you and best regards.

**Comment by willfindlay** [comment]
Hey @BoardzMaster. This repo is currently empty as I'm planning on rewriting bpfbench in Rust when I have more free time. Here is a link to the archived version of what I used in my thesis, although I have no guarantees about how it runs on different kernels: https://github.com/willfindlay/bpfbench-depcrecated. You can also check out the list of tools in https://github.com/iovisor/bcc as they might also apply to your use case.
